Pandas

In [2]:
# import pandas

import pandas as pd

In [3]:
import numpy as np

In [14]:
# Data frame

df = pd.DataFrame(np.arange(0,50,2).reshape(5,5),index = ['R1','R2','R3','R4','R5'],columns = ['C1','C2','C3','C4','C5'])
df

    C1  C2  C3  C4  C5
R1   0   2   4   6   8
R2  10  12  14  16  18
R3  20  22  24  26  28
R4  30  32  34  36  38
R5  40  42  44  46  48

In [15]:
df.to_csv('Test.csv')

In [16]:
df.loc['R1']               # To Access one index

C1    0
C2    2
C3    4
C4    6
C5    8
Name: R1, dtype: int64

In [17]:
type(df.loc['R1'])

pandas.core.series.Series

In [18]:
df[['C1','C2']]

    C1  C2
R1   0   2
R2  10  12
R3  20  22
R4  30  32
R5  40  42

In [19]:
df.iloc[:,:]           # To Access Row and Column

    C1  C2  C3  C4  C5
R1   0   2   4   6   8
R2  10  12  14  16  18
R3  20  22  24  26  28
R4  30  32  34  36  38
R5  40  42  44  46  48

In [20]:
df.iloc[:2,:2]

    C1  C2
R1   0   2
R2  10  12

In [21]:
df.iloc[:,:1] , type(df.iloc[:,:])

(    C1
 R1   0
 R2  10
 R3  20
 R4  30
 R5  40,
 pandas.core.frame.DataFrame)

To Convert DataFrame Into array values

In [22]:
df.iloc[:,:4].values

array([[ 0,  2,  4,  6],
       [10, 12, 14, 16],
       [20, 22, 24, 26],
       [30, 32, 34, 36],
       [40, 42, 44, 46]])

In [23]:
# To Check Null Values

df.isnull().sum()

C1    0
C2    0
C3    0
C4    0
C5    0
dtype: int64

In [24]:
df.value_counts()        # returns count of the values appear in the input

C1  C2  C3  C4  C5
0   2   4   6   8     1
10  12  14  16  18    1
20  22  24  26  28    1
30  32  34  36  38    1
40  42  44  46  48    1
Name: count, dtype: int64

In [25]:
df['C1'].unique()       # returns unique values in the dataframe

array([ 0, 10, 20, 30, 40])

In [26]:
df.head()               # returns first 5 records

    C1  C2  C3  C4  C5
R1   0   2   4   6   8
R2  10  12  14  16  18
R3  20  22  24  26  28
R4  30  32  34  36  38
R5  40  42  44  46  48

In [27]:
import pandas as pd


# To Read a Input file as DataFrame

df = pd.read_csv("steel_dataset.csv")
df.head()

,steel_grade,yield_strength,cross_section_area,load_applied,length,temperature,stress,slenderness_ratio,load_factor,safety_factor,failure_load
0,S355,343.881199,262.397808,25808.361217,5.330881,32.078051,98.355857,0.020316,75.050225,3.496296,24152.929131
1,A992,345.305256,272.729987,38340.450985,2.521211,26.732950,140.580255,0.009244,111.033500,2.456286,26256.574712
2,S355,355.222218,359.944389,24666.566321,5.868778,6.293994,68.528826,0.016305,69.439818,5.183545,29826.096482
3,A992,351.424646,386.705157,105994.040674,4.401538,21.534948,274.095234,0.011382,301.612428,1.282126,33801.169834
4,A572,338.997461,239.068846,88423.302651,3.200762,-1.457324,369.865435,0.013388,260.837654,0.916543,24998.132051

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   steel_grade         50000 non-null  object
 1   yield_strength      50000 non-null  float64
 2   cross_section_area  50000 non-null  float64
 3   load_applied        50000 non-null  float64
 4   length              50000 non-null  float64
 5   temperature         50000 non-null  float64
 6   stress              50000 non-null  float64
 7   slenderness_ratio   50000 non-null  float64
 8   load_factor         50000 non-null  float64
 9   safety_factor       50000 non-null  float64
 10  failure_load        50000 non-null  float64
dtypes: float64(10), object(1)
memory usage: 4.2+ MB

In [29]:
df.describe()

,yield_strength,cross_section_area,load_applied,length,temperature,stress,slenderness_ratio,load_factor,safety_factor,failure_load
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,315.097764,400.277029,69891.697878,3.497464,25.056081,191.904102,0.009586,226.836318,2.266250,31540.685615
std,44.818631,115.232878,28819.240782,1.441924,20.196151,103.813232,0.005162,101.131002,1.497716,11341.141002
min,213.119762,200.010497,20002.232405,1.000046,-9.999839,33.649706,0.001689,53.871715,0.411859,-4270.416454
25%,269.047008,300.042936,45031.648327,2.240655,7.612992,112.177040,0.005620,142.396325,1.236015,22990.085226
50%,339.525020,400.675060,69797.076236,3.506551,24.966139,174.907410,0.008742,221.736683,1.799278,30943.396806
75%,352.315564,499.295240,94744.717496,4.749073,42.488534,247.624561,0.012354,300.914900,2.818666,39665.420910
max,394.621347,599.957067,119995.998003,5.999988,59.998318,598.983991,0.029675,532.954505,10.657958,67507.104300

In [30]:
df['steel_grade'].value_counts()

steel_grade
A992    10134
A36     10013
A572    10002
S355     9926
S275     9925
Name: count, dtype: int64

CSV

In [31]:
# CSV File Creation


from io import StringIO, BytesIO

data = ('c1,c2,c3\n'
        'a,b,c\n'
        'd,e,f\n'
        '1,2,3')

In [32]:
type(data)

str

In [33]:
pd.read_csv(StringIO(data))

  c1 c2 c3
0  a  b  c
1  d  e  f
2  1  2  3

In [35]:
# read from specific column

df = pd.read_csv(StringIO(data),usecols = ['c1','c3'])

In [36]:
df

  c1 c3
0  a  c
1  d  f
2  1  3

In [38]:
df.to_csv("str_to_csv.csv")

Custom datatype

In [52]:
# Specify column data type

data = ('a,b,c,d\n'
        '1,2,3.1,4\n'
        '5,6,7.5,8\n'
        '2,3,4.6,5')

In [53]:
print(data)

a,b,c,d
1,2,3.1,4
5,6,7.5,8
2,3,4.6,5

In [54]:
df = pd.read_csv(StringIO(data),dtype = object)     # specify as entire data frame

In [55]:
print(type(df))
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       3 non-null      object
dtypes: object(4)
memory usage: 228.0+ bytes
None

   a  b    c  d
0  1  2  3.1  4
1  5  6  7.5  8
2  2  3  4.6  5

In [61]:
# specify dtype for specific columns

df = pd.read_csv(StringIO(data),dtype = {'a':'int32','b':'Int64','c':float,'d':object})

In [62]:
print(df.info())
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int32
 1   b       3 non-null      Int64
 2   c       3 non-null      float64
 3   d       3 non-null      object
dtypes: Int64(1), float64(1), int32(1), object(1)
memory usage: 219.0+ bytes
None

   a  b    c  d
0  1  2  3.1  4
1  5  6  7.5  8
2  2  3  4.6  5

In [64]:
# To check data types

df.dtypes

a      int32
b      Int64
c    float64
d     object
dtype: object

In [67]:
pd.read_csv(StringIO(data),index_col = 1)      # set index value as needed

   a    c  d
b
2  1  3.1  4
6  5  7.5  8
3  2  4.6  5

In [69]:
pd.read_csv(StringIO(data))

   a  b    c  d
0  1  2  3.1  4
1  5  6  7.5  8
2  2  3  4.6  5

In [68]:
pd.read_csv(StringIO(data),index_col = False)

   a  b    c  d
0  1  2  3.1  4
1  5  6  7.5  8
2  2  3  4.6  5

In [70]:
# Combine usecols and index_col

pd.read_csv(StringIO(data),usecols = ['a','b'],index_col = False)

   a  b
0  1  2
1  5  6
2  2  3

# Quoting and Escape caracters. usefull in NLP

data = 'a,b\n"Hello, \\"BOB\\",nice to see you",5'

In [74]:
pd.read_csv(StringIO(data),escapechar = "\\")

                              a  b
0  Hello, "BOB",nice to see you  5